### ISSUE TITLE
NPE while obtaining gateway

### ISSUE THREAD

**Issue by TheShark34** [nerd/Discord4J#10]
Hi,

I was trying to use the API, but while I logging in, I obtain this :

java.lang.NullPointerException
	at sx.blah.discord.DiscordClient.obtainGateway(DiscordClient.java:193) ~[Discord4J-1.0-SNAPSHOT.jar:?]
	at sx.blah.discord.DiscordClient.login(DiscordClient.java:178) ~[Discord4J-1.0-SNAPSHOT.jar:?]
	at fr.theshark34.krobot.Krobot.start(Krobot.java:58) [main/:?]
	at fr.theshark34.krobot.Krobot.main(Krobot.java:121) [main/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:?]

:/

**Comment by nerd** [comment]
Hey,

Could you double-check your login info for me?

Thanks.

**Comment by TheShark34** [comment]
Oh yeah it was that, but it is normal that it throws a NPE when the logging infos are invalid ?
Also i saw it uses slf to log sometimes, it is possible to disable that ?

**Comment by nerd** [comment]
I'll add an error message for invalid logins.
