### ISSUE TITLE
UnresolvedAddressException

### ISSUE THREAD

**Issue by lorddusk** [nerd/Discord4J#3]
Upon launching the bot, since last night it gave me the UnresolvedAddressException error.

```
java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:123)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
```

It seems like the Websocket address changed, but I've not been able to find the source of the issue...

**Comment by nerd** [comment]
I'll look into it. If you could grab the location of the websocket using inspect element on the discord web client, that'd be very helpful. If it doesn't show up under the category called "WS" or "WebSocket" in the network tab, refresh the page.

I changed the websocket endpoint recently because it had changed. Are you using the latest version of Discord4J?

**Comment by lorddusk** [comment]
Endpoint now is ws://gateway-zerg.discord.gg/
